### ISSUE TITLE
Eclipse下导入报错

### ISSUE THREAD

**Issue by wangjinyu501** [wangjiegulu/DraggableFlagView#3]
float value = (float) animation.getAnimatedValue();在这行代码，提示：Cannot cast from Object to float。请问如何解决。

**Comment by wangjiegulu** [comment]
用的是哪个版本的jdk？

**Comment by wangjinyu501** [comment]
最新的，5.0的sdk

**Comment by wangjiegulu** [comment]
额 我是问jdk，1.7？

**Comment by wangjinyu501** [comment]
jdk 1.8，和这个有关系吗？

**Comment by ghost** [comment]
还有几个类并没有在工程里，Animator等，。。不能用

**Comment by ghost** [comment]
呃啊，知道了啊。。搞定了，谢谢～
